# Generated by Django 3.2.3 on 2022-06-14 19:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesInformatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Antecedentes de la Informática',
                'verbose_name_plural': 'Antecedentes de la Informática',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255, verbose_name='Título')),
                ('frase', models.TextField(verbose_name='Subtítulo')),
                ('imagen', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name': 'Cintillo con frase',
                'verbose_name_plural': 'Cintillo con frase',
            },
        ),
        migrations.CreateModel(
            name='InformaticaCuba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'La Informática en Cuba',
                'verbose_name_plural': 'La Informática en Cuba',
            },
        ),
    ]
