# Generated by Django 3.2.12 on 2022-06-02 19:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesInformatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InformaticaCuba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalidadDestacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_muerte', models.DateField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='personalidades/')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('foto', models.ImageField(upload_to='maquinas/')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.generacion')),
            ],
        ),
    ]
