# Generated by Django 3.2.3 on 2022-06-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_jugador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
