# Generated by Django 3.2.3 on 2022-06-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20220614_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AntecedentesInformatica',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='InformaticaCuba',
        ),
    ]
